### ISSUE TITLE
A API não estar acessivel!

### ISSUE THREAD

**Issue by D3v-Ru1m** [ClaudioMendonca-Eng/santander-dev-week-26-03-24#1]
O projeto não está funcionando corretamente, pois a API não está acessível.

**Comment by ClaudioMendonca-Eng** [comment]
Gostaríamos de pedir desculpas pelo inconveniente recente. A API que estava hospedada na AWS foi deletada, o que resultou em problemas de acesso ao serviço. Estou trabalhando para resolver a situação o mais rápido possível e estou criando uma nova API no Render.

Agradecemos pela sua paciência e compreensão.

Atenciosamente,
Claudio Mendonça
